from torch_rl.policies.AlphaMixturePolicy import AlphaMixturePolicy
from torch_rl.policies.DiscreteEpsilonGreedyPolicy import DiscreteEpsilonGreedyPolicy
from torch_rl.policies.DiscreteModelPolicy import DiscreteModelPolicy
from torch_rl.policies.DiscreteRandomPolicy import DiscreteRandomPolicy
from torch_rl.policies.Policy import Policy
