# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0012_auto_20170221_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='time_seconds',
        ),
        migrations.AddField(
            model_name='frame',
            name='frame_index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
