# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0016_framelabel_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='framelabel',
            name='video',
            field=models.ForeignKey(default=455, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Video'),
            preserve_default=False,
        ),
    ]
