# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0019_auto_20170222_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
