# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0020_auto_20170222_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tevent',
            old_name='recorded',
            new_name='created',
        ),
        migrations.AddField(
            model_name='tevent',
            name='seconds',
            field=models.FloatField(default=-1),
        ),
    ]
