# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0021_auto_20170223_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='parent_query',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dvaapp.Query'),
        ),
        migrations.AddField(
            model_name='video',
            name='query',
            field=models.BooleanField(default=False),
        ),
    ]
