# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvaapp', '0022_auto_20170225_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryresults',
            name='rank',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
